### ISSUE TITLE
Cannot find module '@babel/core'

### ISSUE THREAD

**Issue by DennisKo** [pikapkg/builders#11]
package.json
```
"@pika/pack": {
    "pipeline": [
      [
        "@pika/plugin-ts-standard-pkg"
      ],
      ["@pika/plugin-build-web"]
    ]
  },
  "devDependencies": {
    "@pika/plugin-build-types": "^0.3.11",
    "@pika/plugin-build-web": "^0.3.11",
    "@pika/plugin-ts-standard-pkg": "^0.3.11"
  }
```

pack build..

```
Error: Cannot find module '@babel/core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

It can be fixed with `yarn add -D @babel/core` but that should probably be a dependency.

**Comment by FredKSchott** [comment]
Doh, looks like rollup-plugin-babel defines it as a peer dep and not a real dep. We should add this as a dependency of @pika/plugin-build-web 

See: https://unpkg.com/rollup-plugin-babel@4.3.2/package.json

**Comment by FredKSchott** [comment]
Fixed
