### ISSUE TITLE
Error: Unexpected token in @pika/plugin-build-web

### ISSUE THREAD

**Issue by Jack-Works** [pikapkg/builders#115]
```
[5/8] Running @pika/plugin-build-web...
Error: Unexpected token
    at error (node_modules\rollup\dist\shared\node-entry.js:5400:30)
    at Module.error (node_modules\rollup\dist\shared\node-entry.js:9824:16)
    at tryParse (node_modules\rollup\dist\shared\node-entry.js:9717:23)
    at Module.setSource (node_modules\rollup\dist\shared\node-entry.js:10080:33)
```

Code base: https://github.com/Jack-Works/async-call/tree/pika

**Comment by arnohovhannisyan** [comment]
I'm getting the same error when trying to use optional chaining (`?.`) and nullish coalescing (`??`) with `@pika/plugin-ts-standard-pkg`. When I stopped using these two features, the build completed successfully.

**Comment by Jack-Works** [comment]
@FredKSchott please enable as more babel syntaxes as possible 🙈 it's blocking

**Comment by kripod** [comment]
I can confirm the statements of @arnohovhannisyan, just bumped into it now:

```
[5/6] Running @pika/plugin-build-web...
Error: Unexpected token
    at error (C:\Projects\react-typed-inputs\node_modules\rollup\dist\shared\node-entry.js:5400:30)
    at Module.error (C:\Projects\react-typed-inputs\node_modules\rollup\dist\shared\node-entry.js:9824:16)
    at tryParse (C:\Projects\react-typed-inputs\node_modules\rollup\dist\shared\node-entry.js:9717:23)
    at Module.setSource (C:\Projects\react-typed-inputs\node_modules\rollup\dist\shared\node-entry.js:10080:33)
    at C:\Projects\react-typed-inputs\node_modules\rollup\dist\shared\node-entry.js:12366:20
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
Error: Command failed with exit code 1 (Unknown system error -1): npx pika-pack
    at makeError (C:\Projects\react-typed-inputs\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Projects\react-typed-inputs\node_modules\execa\index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runExternalCommand (C:\Projects\react-typed-inputs\node_modules\@pika\cli\dist-node\index.js:83:5)
    at async cli (C:\Projects\react-typed-inputs\node_modules\@pika\cli\dist-node\index.js:141:43)
error Command failed with exit code 1.
```

**Comment by kripod** [comment]
I can confirm the statements of @arnohovhannisyan, just bumped into it now:

This is probably caused by the recent migration to the `ES2020` compilation target (#106). Rollup might not be ready for it yet.

**Comment by FredKSchott** [comment]
Great find! updating to Rollup v2+ SHOULD fix this, let me see if that works

**Comment by FredKSchott** [comment]
Looks like it works, but will test a bit more before releasing

**Comment by Jack-Works** [comment]
> Looks like it works, but will test a bit more before releasing

maybe should set rollup to peer dependency to allow users to upgrade their rollup version instead

**Comment by FredKSchott** [comment]
That could also work, but it would have hit this same problem, since Rollup went from v1 -> v2 and didn't match the semver regardless of where it was in the package.json

**Comment by Jack-Works** [comment]
You can write "rollup": "*"

**Comment by Jack-Works** [comment]
@FredKSchott hi please release a new version on npm for the fix...

**Comment by Averethel** [comment]
@FredKSchott Any chance we can get a release that is updated to rollup 2.0?

**Comment by diyorbek** [comment]
@FredKSchott Are there any updates on releasing the fix?
