### ISSUE TITLE
@pika/plugin-bundle-web errors out on dynamic imports

### ISSUE THREAD

**Issue by rafamel** [pikapkg/builders#55]
Dynamic imports (`import('./foo').then(...)`) error out on `@pika/plugin-bundle-web`:

```
Error: You must set "output.dir" instead of "output.file" when generating multiple chunks.
    at error (node_modules/rollup/dist/rollup.js:9236:30)
    at normalizeOutputOptions (node_modules/rollup/dist/rollup.js:17130:13)
    at getOutputOptions (node_modules/rollup/dist/rollup.js:16888:24)
    at Object.write (node_modules/rollup/dist/rollup.js:16980:43)
    at Object.build (node_modules/@pika/plugin-build-web/dist-node/index.js:62:16)
    at <anonymous>
```

This is related to the rollup write. Changing it to the following should solve it:

```javascript
const writeToWeb = path.join(out, 'dist-web');
await result.write({
  dir: writeToWeb,
  format: 'esm',
  exports: 'named',
});
```

**Comment by FredKSchott** [comment]
Great catch! Fixed in https://github.com/pikapkg/builders/commit/dc68c2799fffcedc86a8bb5099ee2aef82b5dc71
