### ISSUE TITLE
@pika/plugin-ts-standard-pkg crashes when jest@24 is added

### ISSUE THREAD

**Issue by varna** [pikapkg/builders#66]
1. `git clone https://github.com/pikapkg/examples/tree/master/typescript-package`
2. `yarn add jest -D`
3. `pika build`
4. Crash:
```
Error: Command failed: /Users/varna/Code/examples/typescript-package/node_modules/.bin/tsc --outDir /Users/varna/Code/examples/typescript-package/pkg/dist-src/ -d --declarationDir /Users/varna/Code/examples/typescript-package/pkg/dist-types/ --project /Users/varna/Code/examples/typescript-package/tsconfig.json --declarationMap false --target es2018 --module esnext

node_modules/@types/babel__core/index.d.ts(13,20): error TS2307: Cannot find module '@babel/types'.
node_modules/@types/babel__core/index.d.ts(14,31): error TS2307: Cannot find module '@babel/parser'.
node_modules/@types/babel__generator/index.d.ts(9,20): error TS2307: Cannot find module '@babel/types'.
node_modules/@types/babel__template/index.d.ts(9,31): error TS2307: Cannot find module '@babel/parser'.
node_modules/@types/babel__template/index.d.ts(10,54): error TS2307: Cannot find module '@babel/types'.
node_modules/@types/babel__traverse/index.d.ts(10,20): error TS2307: Cannot find module '@babel/types'.
node_modules/@types/babel__traverse/index.d.ts(30,5): error TS2411: Property 'scope' of type 'Scope | undefined' is not assignable to string index type '(VisitNodeFunction<S, any> & VisitNodeObject<S, any>) | (VisitNodeFunction<S, any> & VisitNodeFunction<S, any>) | (VisitNodeObject<S, any> & VisitNodeObject<S, any>) | (VisitNodeObject<...> & VisitNodeFunction<...>) | undefined'.
node_modules/@types/babel__traverse/index.d.ts(31,5): error TS2411: Property 'noScope' of type 'boolean | undefined' is not assignable to string index type '(VisitNodeFunction<S, any> & VisitNodeObject<S, any>) | (VisitNodeFunction<S, any> & VisitNodeFunction<S, any>) | (VisitNodeObject<S, any> & VisitNodeObject<S, any>) | (VisitNodeObject<...> & VisitNodeFunction<...>) | undefined'.

    at makeError (/Users/varna/Code/examples/typescript-package/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/varna/Code/examples/typescript-package/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I know that I added another package (p.s. jest@23 works), but I don't even use it (in reproduction). And it crashes whole build process.

**Comment by FredKSchott** [comment]
This feels like a TypeScript error with Jest / `@types/babel__core`, I've never seen that package before so I don't really know how to help with this one

**Comment by varna** [comment]
Thanks for reply!
I did more digging. Found https://github.com/DefinitelyTyped/DefinitelyTyped/issues/27729#issuecomment-486271169 and https://github.com/facebook/jest/issues/8218#issuecomment-486283127

So, adding this to `tsconfig.json` worked for me:
```json
{
  "compilerOptions": {
    "moduleResolution": "node"
  }
}
```
