### ISSUE TITLE
Support code splitting.

### ISSUE THREAD

**Issue by MarkLyck** [pikapkg/builders#91]
When I try to do anything with react-loadable. I get this error:

`Error: You must set "output.dir" instead of "output.file" when generating multiple chunks.`

But there's no where to set those settings...

full output:

```
Running @pika/plugin-build-web...
Error: You must set "output.dir" instead of "output.file" when generating multiple chunks.
    at error (/Users/marklyck/colony/colony-ui/node_modules/rollup/dist/rollup.js:5325:30)
    at normalizeOutputOptions (/Users/marklyck/colony/colony-ui/node_modules/rollup/dist/rollup.js:13585:13)
    at getOutputOptions (/Users/marklyck/colony/colony-ui/node_modules/rollup/dist/rollup.js:13369:20)
    at Object.write (/Users/marklyck/colony/colony-ui/node_modules/rollup/dist/rollup.js:13437:39)
    at Object.build (/Users/marklyck/colony/colony-ui/node_modules/@pika/plugin-build-web/dist-node/index.js:48:16)
    at async /Users/marklyck/colony/colony-ui/node_modules/@pika/pack/dist-node/index.js:2375:11
    at async Build.init (/Users/marklyck/colony/colony-ui/node_modules/@pika/pack/dist-node/index.js:2459:7)
    at async Object.run (/Users/marklyck/colony/colony-ui/node_modules/@pika/pack/dist-node/index.js:2467:3)
Error: Command failed with exit code 1 (EPERM): npx pika-pack
    at makeError (/Users/marklyck/colony/colony-ui/node_modules/@pika/cli/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/marklyck/colony/colony-ui/node_modules/@pika/cli/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runExternalCommand (/Users/marklyck/colony/colony-ui/node_modules/@pika/cli/dist-node/index.js:83:5)
    at async cli (/Users/marklyck/colony/colony-ui/node_modules/@pika/cli/dist-node/index.js:141:43)
error Command failed with exit code 1.
```

**Comment by FredKSchott** [comment]
Same issue as the one discussed here: https://www.pika.dev/npm/@pika/pack/discuss/2
